In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/earthquake_1995-2023.csv')
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16/08/2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19/07/2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17/07/2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16/07/2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16/07/2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   date_time  1000 non-null   object
 3   cdi        1000 non-null   int64
 4   mmi        1000 non-null   int64
 5   alert      449 non-null    object
 6   tsunami    1000 non-null   int64
 7   sig        1000 non-null   int64
 8   net        1000 non-null   object
 9   nst        1000 non-null   int64
 10  dmin       1000 non-null   float64
 11  gap        1000 non-null   float64
 12  magType    1000 non-null   object
 13  depth      1000 non-null   float64
 14  latitude   1000 non-null   float64
 15  longitude  1000 non-null   float64
 16  location   994 non-null    object
 17  continent  284 non-null    object
 18  country    651 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 148.6+ KB

In [4]:
df.columns

Index(['title', 'magnitude', 'date_time', 'cdi', 'mmi', 'alert', 'tsunami',
       'sig', 'net', 'nst', 'dmin', 'gap', 'magType', 'depth', 'latitude',
       'longitude', 'location', 'continent', 'country'],
      dtype='object')

In [5]:
df.shape

(1000, 19)

In [6]:
df.head(2)

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16/08/2023 12:47,7,4,green,0,657,us,114,7.177,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19/07/2023 00:22,8,6,yellow,0,775,us,92,0.679,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN

In [7]:
df.describe()

,magnitude,cdi,mmi,tsunami,sig,nst,dmin,gap,depth,latitude,longitude
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,6.940150,3.605000,6.02700,0.325000,847.915000,193.918000,1.125174,20.926290,74.612541,4.315554,51.486576
std,0.438148,3.328972,1.43399,0.468609,301.802632,239.045858,2.073164,24.415895,130.812590,26.633320,117.478302
min,6.500000,0.000000,1.00000,0.000000,650.000000,0.000000,0.000000,0.000000,2.700000,-61.848400,-179.968000
25%,6.600000,0.000000,5.00000,0.000000,691.000000,0.000000,0.000000,0.000000,16.000000,-13.518500,-71.694450
50%,6.800000,4.000000,6.00000,0.000000,744.000000,0.000000,0.000000,18.000000,29.000000,-2.443500,107.791000
75%,7.100000,7.000000,7.00000,1.000000,874.250000,403.000000,1.549250,27.000000,55.000000,25.167250,148.364750
max,9.100000,9.000000,10.00000,1.000000,2910.000000,934.000000,17.654000,239.000000,670.810000,71.631200,179.662000

In [8]:
df.isna().sum()

title          0
magnitude      0
date_time      0
cdi            0
mmi            0
alert        551
tsunami        0
sig            0
net            0
nst            0
dmin           0
gap            0
magType        0
depth          0
latitude       0
longitude      0
location       6
continent    716
country      349
dtype: int64

In [9]:
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16/08/2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19/07/2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17/07/2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16/07/2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16/07/2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

In [10]:
df[df['alert']=="green"]

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16/08/2023 12:47,7,4,green,0,657,us,114,7.177,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17/07/2023 03:05,7,5,green,0,899,us,70,1.634,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16/07/2023 06:48,6,6,green,1,860,us,173,0.907,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
5,"M 6.6 - 277 km NNE of Codrington, Antigua and ...",6.6,10/07/2023 20:28,5,4,green,1,802,us,95,2.454,37.0,mww,10.000,20.0196,-61.0955,"Codrington, Antigua and Barbuda",NaN,NaN
6,M 6.9 - Tonga,6.9,02/07/2023 10:27,4,4,green,1,741,us,136,1.179,23.0,mww,229.000,-17.8530,-174.9370,Tonga,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,"M 7.0 - 33 km NW of Lata, Solomon Islands",7.0,06/02/2013 01:54,0,6,green,0,754,us,445,0.000,17.5,mww,8.800,-10.4990,165.5880,"Lata, Solomon Islands",NaN,Solomon Islands
448,"M 7.1 - 112 km WSW of Lata, Solomon Islands",7.1,06/02/2013 01:23,0,5,green,0,776,us,550,0.000,18.4,mww,10.000,-11.1830,164.8820,"Lata, Solomon Islands",NaN,NaN
449,"M 8.0 - 75 km W of Lata, Solomon Islands",8.0,06/02/2013 01:12,8,7,green,1,993,us,460,0.000,20.9,mww,24.000,-10.7990,165.1140,"Lata, Solomon Islands",NaN,NaN
451,"M 6.8 - 54 km N of Vallenar, Chile",6.8,30/01/2013 20:15,6,7,green,0,771,us,596,0.000,19.3,mww,45.000,-28.0940,-70.6530,"Vallenar, Chile",South America,Chile
475,M 8.2 - off the west coast of northern Sumatra,8.2,11/04/2012 10:43,9,6,green,0,1213,us,341,0.000,14.9,mwc,25.100,0.8020,92.4630,off the west coast of northern Sumatra,NaN,NaN

In [11]:
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16/08/2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19/07/2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17/07/2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16/07/2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16/07/2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

In [12]:
df(df["tsunami"]==1).sum()

TypeError: 'DataFrame' object is not callable

In [13]:
df.loc[10:20]

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
10,M 7.7 - southeast of the Loyalty Islands,7.7,19/05/2023 02:57,5,4,green,1,927,us,277,3.111,15.0,mww,18.027,-23.2286,170.6940,the Loyalty Islands,NaN,NaN
11,"M 7.6 - 95 km WNW of Hihifo, Tonga",7.6,10/05/2023 16:02,8,6,green,1,907,us,111,3.631,17.0,mww,210.097,-15.6002,-174.6080,"Hihifo, Tonga",NaN,NaN
12,M 6.6 - south of the Fiji Islands,6.6,28/04/2023 03:13,0,2,green,0,670,us,52,5.123,50.0,mww,598.467,-25.2657,178.4240,the Fiji Islands,NaN,NaN
13,"M 7.1 - 170 km SSE of Teluk Dalam, Indonesia",7.1,24/04/2023 20:00,9,7,green,0,838,us,70,2.282,58.0,mww,15.462,-0.7810,98.5339,"Teluk Dalam, Indonesia",NaN,Indonesia
14,"M 7.1 - Kermadec Islands, New Zealand",7.1,24/04/2023 00:41,8,7,green,1,777,us,126,0.708,23.0,mww,43.063,-30.0249,-177.8970,"Kermadec Islands, New Zealand",NaN,NaN
15,M 6.7 - south of the Fiji Islands,6.7,18/04/2023 04:31,0,3,green,1,691,us,166,4.719,10.0,mww,595.854,-22.2844,179.3910,the Fiji Islands,NaN,NaN
16,"M 7.0 - 96 km N of Tuban, Indonesia",7.0,14/04/2023 09:55,5,3,green,0,818,us,131,1.881,31.0,mww,594.028,-6.0255,112.0330,"Tuban, Indonesia",NaN,Indonesia
17,M 6.5 - near the east coast of the Kamchatka P...,6.5,03/04/2023 03:06,7,6,yellow,1,655,us,104,0.266,30.0,mww,105.631,52.7772,158.4840,"the Kamchatka Peninsula, Russia",Asia,Russian Federation (the)
18,"M 7.0 - New Guinea, Papua New Guinea",7.0,02/04/2023 18:04,7,7,green,1,781,us,105,6.450,31.0,mww,62.603,-4.2924,143.1550,"New Guinea, Papua New Guinea",Asia,Papua New Guinea
19,M 6.5 - 84 km NNW of San Antonio de los Cobres...,6.5,22/03/2023 16:00,4,4,green,0,656,us,97,1.622,33.0,mww,209.976,-23.4797,-66.5108,"San Antonio de los Cobres, Argentina",South America,Argentina
20,"M 6.5 - 40 km SSE of Jurm, Afghanistan",6.5,21/03/2023 16:47,7,5,green,0,1350,us,134,2.530,13.0,mww,187.589,36.5227,70.9787,"Jurm, Afghanistan",Asia,Afghanistan

In [14]:
(df["tsunami"] == 1).sum()

np.int64(325)

In [15]:
df["tsunami"].value_counts()

tsunami
0    675
1    325
Name: count, dtype: int64

In [16]:
print("No.of Rows and Columns are:", df.shape)

No.of Rows and Columns are: (1000, 19)

In [17]:
df.columns

Index(['title', 'magnitude', 'date_time', 'cdi', 'mmi', 'alert', 'tsunami',
       'sig', 'net', 'nst', 'dmin', 'gap', 'magType', 'depth', 'latitude',
       'longitude', 'location', 'continent', 'country'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   date_time  1000 non-null   object
 3   cdi        1000 non-null   int64
 4   mmi        1000 non-null   int64
 5   alert      449 non-null    object
 6   tsunami    1000 non-null   int64
 7   sig        1000 non-null   int64
 8   net        1000 non-null   object
 9   nst        1000 non-null   int64
 10  dmin       1000 non-null   float64
 11  gap        1000 non-null   float64
 12  magType    1000 non-null   object
 13  depth      1000 non-null   float64
 14  latitude   1000 non-null   float64
 15  longitude  1000 non-null   float64
 16  location   994 non-null    object
 17  continent  284 non-null    object
 18  country    651 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 148.6+ KB

In [19]:
df.isnull().sum()

title          0
magnitude      0
date_time      0
cdi            0
mmi            0
alert        551
tsunami        0
sig            0
net            0
nst            0
dmin           0
gap            0
magType        0
depth          0
latitude       0
longitude      0
location       6
continent    716
country      349
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
dupe_mask=df.duplicated(subset=['title','date_time'],keep=False)
print("Rows involved in a title+date_time duplicate:",dupe_mask.sum())
before=len(df)

Rows involved in a title+date_time duplicate: 4

In [22]:
df[dupe_mask].sort_values('title')[["title","date_time","magnitude","country"]]

                                   title         date_time  magnitude country
67  M 6.5 - 71 km SE of Nikolski, Alaska  11/01/2022 12:39        6.5     NaN
68  M 6.5 - 71 km SE of Nikolski, Alaska  11/01/2022 12:39        6.5     NaN
70  M 6.7 - 91 km SE of Nikolski, Alaska  11/01/2022 11:35        6.7     NaN
71  M 6.7 - 91 km SE of Nikolski, Alaska  11/01/2022 11:35        6.7     NaN

In [23]:
df=df.drop_duplicates(subset=['title','date_time'],keep='first').reset_index(drop=True)

In [24]:
df.loc[66:71,["title","magnitude","date_time"]]

                                    title  magnitude         date_time
66  M 6.6 - 80 km SW of Labuan, Indonesia        6.6  14/01/2022 09:05
67   M 6.5 - 71 km SE of Nikolski, Alaska        6.5  11/01/2022 12:39
68   M 6.6 - 53 km SE of Nikolski, Alaska        6.6  11/01/2022 12:39
69   M 6.7 - 91 km SE of Nikolski, Alaska        6.7  11/01/2022 11:35
70  M 6.8 - 100 km SE of Nikolski, Alaska        6.8  11/01/2022 11:35
71     M 6.6 - 48 km WNW of Pólis, Cyprus        6.6  11/01/2022 01:07

In [25]:
missing=df.isnull().sum()

In [26]:
missing_report=(
    pd.DataFrame({
        "missing_count":missing,
        "missing_percentage":(missing/len(df)*100).round(1),
    })
    .query("missing_count>0")
    .sort_values("missing_count",ascending=False)
)
missing_report

           missing_count  missing_percentage
continent            714                71.5
alert                549                55.0
country              347                34.8
location               6                 0.6

In [27]:
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16/08/2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19/07/2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17/07/2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16/07/2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16/07/2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

In [28]:
zeros=df.isna().sum()
for i,j in zeros.items():
  if j==0:
    continue
  else:
    print(i,j)

alert 549
location 6
continent 714
country 347

In [29]:
import numpy as np
for col in ["cdi","gap"]:
  df[col]=df[col].replace(0,np.nan)
print("Missing Values now visible:")
print(df[["cdi","gap"]].isnull().sum())

Missing Values now visible:
cdi    395
gap    252
dtype: int64

In [30]:
# Filling the missing nuber with Mean and Median
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16/08/2023 12:47,7.0,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19/07/2023 00:22,8.0,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17/07/2023 03:05,7.0,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16/07/2023 06:48,6.0,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16/07/2023 06:48,NaN,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      998 non-null    object
 1   magnitude  998 non-null    float64
 2   date_time  998 non-null    object
 3   cdi        603 non-null    float64
 4   mmi        998 non-null    int64
 5   alert      449 non-null    object
 6   tsunami    998 non-null    int64
 7   sig        998 non-null    int64
 8   net        998 non-null    object
 9   nst        998 non-null    int64
 10  dmin       998 non-null    float64
 11  gap        746 non-null    float64
 12  magType    998 non-null    object
 13  depth      998 non-null    float64
 14  latitude   998 non-null    float64
 15  longitude  998 non-null    float64
 16  location   992 non-null    object
 17  continent  284 non-null    object
 18  country    651 non-null    object
dtypes: float64(7), int64(4), object(8)
memory usage: 148.3+ KB

In [32]:
df["cdi"].isna().sum()

np.int64(395)

In [33]:
df["cdi"].mean()

np.float64(5.978441127694859)

In [34]:
df["cdi"].median()

6.0

In [35]:
df["cdi"].mode()

0    5.0
Name: cdi, dtype: float64